### ISSUE TITLE
Switch-to-tab no longer works.

### ISSUE THREAD

**Issue by autonome** [ajitk/omnibar#6]
I would LOVE to have this working with Omnibar installed.

**Comment by ajitk** [comment]
You could set the about:config property `extensions.omnibar.disableshowintab` value to `false`.

**Comment by autonome** [comment]
why is it disabled by default?

i'll try it out know, thanks!

**Comment by autonome** [comment]
WORKS, thanks!

**Comment by ajitk** [comment]
Keep it enabled used to trigger a buggy behavior in the auto-complete popup where it used to prefix the text in urlbar with ">>>". It was meant to be a workaround.
